
insert into public.exercises (name, description, muscle_group, difficulty, default_sets, default_reps, default_duration_seconds, default_rest_seconds) values

-- ARMS (32 new)
('Tricep Push-up', 'Hands directly under shoulders, elbows track straight back as you lower. Press back up keeping elbows tight to body.', 'Arms', 'Easy', 3, 10, null, 30),
('Close-Grip Push-up', 'Hands shoulder-width or narrower, lower chest between hands. Emphasizes triceps and inner chest.', 'Arms', 'Easy', 3, 12, null, 30),
('Commando Pull-up', 'Hands staggered on bar, pull chin to one side then alternate. Works biceps and lats unevenly.', 'Arms', 'Medium', 3, 8, null, 45),
('Archer Push-up', 'Wide hand placement, shift weight to one arm as you lower, keeping other arm extended. Alternate sides.', 'Arms', 'Hard', 3, 6, null, 60),
('One-Arm Push-up Progression', 'Full wide-leg one-arm push-up, lower chest to floor with control. Keep hips square.', 'Arms', 'Hard', 3, 5, null, 90),
('Planche Lean', 'In push-up position, lean forward shifting shoulders past hands. Hold body rigid. Build planche strength.', 'Arms', 'Hard', 3, null, 15, 60),
('Hollow Push-up', 'Maintain hollow body position throughout push-up movement. No hip sag, back flat.', 'Arms', 'Medium', 3, 10, null, 45),
('Ring Dip', 'On gymnastic rings, lower body until upper arms parallel to floor. Press back to lockout, turn rings out.', 'Arms', 'Hard', 3, 8, null, 60),
('Negative Pull-up', 'Jump to top position, lower yourself as slowly as possible (5-10 seconds). Build pull strength eccentrically.', 'Arms', 'Medium', 3, 6, null, 60),
('Typewriter Pull-up', 'Pull up, then slide body to one side keeping chin above bar, across and down the other side.', 'Arms', 'Hard', 3, 5, null, 90),
('Band-Assisted Muscle-up', 'With resistance band for assistance, pull explosively from hang to push-up position above bar.', 'Arms', 'Medium', 3, 5, null, 90),
('Towel Pull-up', 'Drape towels over bar, grip one in each hand, perform pull-up. Challenges grip and forearm strength.', 'Arms', 'Medium', 3, 8, null, 60),
('Neutral-Grip Pull-up', 'Parallel grip (palms facing each other), pull chin to bar level. Easier on shoulders than pronated grip.', 'Arms', 'Easy', 3, 8, null, 45),
('Wide-Grip Pull-up', 'Hands wider than shoulder-width, pull chest toward bar. Emphasizes lat width over bicep.', 'Arms', 'Medium', 4, 6, null, 60),
('L-Pull-up', 'Maintain L-sit position (legs parallel to floor) throughout entire pull-up movement. Extreme core demand.', 'Arms', 'Hard', 3, 5, null, 90),
('Fingertip Push-up', 'Push-up on fingertips only. Builds grip strength and finger tendon resilience for bar work.', 'Arms', 'Medium', 3, 10, null, 45),
('Wrist Push-up', 'Push-up on back of wrists (fists facing down). Builds wrist flexor strength and conditioning.', 'Arms', 'Easy', 3, 10, null, 30),
('Scapular Push-up', 'In push-up top position, protract and retract scapulae without bending elbows. Serratus anterior work.', 'Arms', 'Easy', 3, 15, null, 20),
('Superman Push-up', 'Explosive push-up launching hands and feet off ground simultaneously. Land softly.', 'Arms', 'Hard', 3, 6, null, 60),
('Clap Push-up', 'Explosive push-up, clap hands at top before landing. Builds upper body power.', 'Arms', 'Medium', 3, 8, null, 45),
('Assisted One-Arm Pull-up', 'One hand on bar, other hand grips same wrist for assistance. Lower the assistance over time.', 'Arms', 'Hard', 3, 4, null, 90),
('Hang to Row', 'From dead hang, perform inverted row pulling chest to bar. Smooth transition between movements.', 'Arms', 'Medium', 3, 10, null, 45),
('Ring Bicep Curl', 'Stand facing anchor point, lean back with rings at hip level, curl rings to forehead. Adjust angle.', 'Arms', 'Easy', 3, 12, null, 30),
('Pike Handstand Push-up Negative', 'From handstand against wall, lower head slowly toward floor over 5 seconds. Press back up.', 'Arms', 'Hard', 3, 5, null, 90),
('Forearm Curl', 'Kneel, forearms on bench, wrists hanging off edge, curl weight through full wrist range of motion.', 'Arms', 'Easy', 3, 15, null, 20),
('Bar Hang (Active)', 'Dead hang from bar with active shoulder depression and retraction. No passive shrugging.', 'Arms', 'Easy', 3, null, 45, 30),
('Reverse Grip Push-up', 'Hands turned outward 180 degrees (fingers pointing toward feet). Unusual bicep and forearm load.', 'Arms', 'Medium', 3, 8, null, 45),
('Tuck Front Lever Row', 'In tuck front lever position on bar, perform rowing motion pulling chest to bar.', 'Arms', 'Hard', 3, 5, null, 90),
('Elbow Plank to Push-up', 'Alternate between forearm plank and push-up top position one arm at a time. Control the transition.', 'Arms', 'Medium', 3, 10, null, 45),
('Band Tricep Pushdown', 'Anchor band overhead, grip with both hands, extend elbows driving hands toward thighs. Full lockout.', 'Arms', 'Easy', 3, 15, null, 20),
('Gymnastic Ring Push-up Hold', 'Hold top position of ring push-up with rings turned out 45 degrees. Builds ring stability.', 'Arms', 'Medium', 3, null, 20, 30),
('Straddle Planche Lean', 'Legs straddled wide, lean forward on hands shifting center of mass over wrists. Advanced planche prep.', 'Arms', 'Hard', 3, null, 10, 90),

-- BACK (32 new)
('Arch Body Rock', 'In arch body position (prone, arms and legs raised), rock forward and back maintaining shape.', 'Back', 'Easy', 3, 15, null, 30),
('Good Morning', 'Feet hip-width, hinge at hips with flat back until torso parallel to floor. Drive hips forward to stand.', 'Back', 'Easy', 3, 12, null, 30),
('Prone Cobra', 'Lie face down, place hands by hips, press up through hands lifting chest. Hold at top.', 'Back', 'Easy', 3, null, 20, 20),
('Single-Arm Row', 'One hand and knee on bench, row dumbbell or band to hip with other arm. Squeeze at top.', 'Back', 'Easy', 3, 12, null, 30),
('Renegade Row', 'In push-up position with weights, row one arm at a time. Keep hips square throughout.', 'Back', 'Medium', 3, 10, null, 45),
('Stiff-Leg Deadlift', 'Hinge at hips with minimal knee bend, lower weights to mid-shin, drive hips to stand. Hamstring and back.', 'Back', 'Medium', 3, 10, null, 45),
('GHD Raise', 'On glute-ham developer, lower torso below parallel and raise back up. Full range hip extension.', 'Back', 'Medium', 3, 12, null, 45),
('Front Lever Tuck Hold', 'On bar, pull into tucked horizontal hold with arms straight, body parallel to floor.', 'Back', 'Hard', 3, null, 8, 90),
('Front Lever Progression', 'Straddle front lever hold — legs open wide, body horizontal on bar with arms straight.', 'Back', 'Hard', 3, null, 6, 90),
('Negative Front Lever', 'From inverted hang, lower body slowly to horizontal position. Resist throughout the descent.', 'Back', 'Hard', 3, 5, null, 90),
('Straight-Arm Pulldown', 'Stand facing anchor, arms straight, pull hands from overhead to hips. Lats only, no elbow bend.', 'Back', 'Medium', 3, 12, null, 30),
('Band Pull-Down', 'Anchor band overhead, face anchor, pull band to chest keeping arms slightly bent. Full lat contraction.', 'Back', 'Easy', 3, 15, null, 20),
('Dead Hang Shrug', 'From dead hang, depress shoulders pulling body up without bending elbows. Pure scapular control.', 'Back', 'Easy', 3, 12, null, 30),
('Horizontal Pull-up', 'Feet elevated to make body horizontal, pull chest to bar from fully horizontal position. Max lat load.', 'Back', 'Hard', 3, 8, null, 60),
('Mixed Grip Pull-up', 'One hand pronated, one supinated on bar. Pull-up targets bicep and lat differently each set.', 'Back', 'Medium', 3, 8, null, 45),
('Close-Grip Pull-up', 'Hands close together on bar, pull chin over. More bicep involvement than wide grip.', 'Back', 'Medium', 3, 8, null, 45),
('Kipping Pull-up', 'Use hip drive to generate momentum, then pull explosively. Gymnastics conditioning tool for volume.', 'Back', 'Medium', 3, 15, null, 45),
('Chest-to-Bar Pull-up', 'Full pull-up driving chest to touch the bar. Requires greater range and lat strength.', 'Back', 'Hard', 3, 6, null, 60),
('Reverse Hyperextension', 'Lie on elevated surface, hang legs off edge, raise legs to horizontal using glutes and lower back.', 'Back', 'Medium', 3, 12, null, 30),
('Y-T-W Raise', 'Prone on floor, raise arms into Y, then T, then W position. Hits all three lower trap fibers.', 'Back', 'Easy', 3, 10, null, 30),
('Seated Cable Row', 'Sit facing anchor point, feet braced, row handles to lower ribs. Squeeze scapulae at finish.', 'Back', 'Easy', 3, 12, null, 30),
('Face Pull', 'Anchor band at face height, pull toward face with elbows flared high. External rotation and rear delt.', 'Back', 'Easy', 3, 15, null, 20),
('Hollow Body Pull-up', 'Maintain strict hollow body (no arch) throughout pull-up. Gymnastics-specific pulling pattern.', 'Back', 'Hard', 3, 6, null, 60),
('Muscle-up Negative', 'Start at top of muscle-up (in dip position above bar), lower slowly through transition to hang.', 'Back', 'Hard', 3, 4, null, 90),
('Ring Pull-up', 'Pull-up using gymnastic rings. Rings allowed to rotate naturally. More shoulder-friendly than bar.', 'Back', 'Medium', 3, 8, null, 45),
('Prone T Raise', 'Lie face down, raise arms to T position (directly to sides) squeezing rear delts. Lower slowly.', 'Back', 'Easy', 3, 15, null, 20),
('Thoracic Extension', 'Sit upright, hands behind head, extend upper back over a foam roller or the edge of a bench.', 'Back', 'Easy', 3, null, 30, 20),
('Bear Hug Carry', 'Hug a heavy bag or medicine ball to chest, walk for distance maintaining upright posture.', 'Back', 'Medium', 3, null, 30, 30),
('Inverted Hang', 'Hang inverted from bar (toes to bar then extend inverted), hold still. Builds inverted body awareness.', 'Back', 'Medium', 3, null, 15, 45),
('Arch to Hollow on Bar', 'Hang from bar, alternate between arch position and hollow position in a controlled swing cycle.', 'Back', 'Medium', 3, 10, null, 45),
('Banded Good Morning', 'Band anchored under feet and over shoulders, hinge at hips maintaining flat back, stand tall.', 'Back', 'Easy', 3, 15, null, 20),
('Reverse Snow Angel', 'Lie face down arms at sides, trace arms from hips to overhead and back, keeping arms off floor.', 'Back', 'Easy', 3, 10, null, 20);
