
insert into public.exercises (name, description, muscle_group, difficulty, default_sets, default_reps, default_duration_seconds, default_rest_seconds) values

-- LEGS (30 new)
('Squat Hold', 'Deep squat with feet flat, hold at bottom. Builds hip and ankle mobility alongside leg strength.', 'Legs', 'Easy', 3, null, 45, 20),
('Lateral Lunge', 'Step wide to one side, push hips back and bend that knee. Drive through heel back to standing.', 'Legs', 'Easy', 3, 10, null, 30),
('Reverse Lunge', 'Step back onto toes, lower back knee toward floor. Drive through front foot to return. Controlled.', 'Legs', 'Easy', 3, 10, null, 30),
('Step-Up', 'Step onto a box or bench with one foot, drive through heel to stand on top. Step down controlled.', 'Legs', 'Easy', 3, 12, null, 30),
('Skater Squat', 'Single-leg squat lowering back knee toward floor. Non-working leg trails behind, no support.', 'Legs', 'Hard', 3, 6, null, 60),
('Cossack Squat', 'Wide stance, shift weight fully to one side into deep squat while extending opposite leg out flat.', 'Legs', 'Medium', 3, 8, null, 45),
('Sumo Squat', 'Wide stance with toes pointed out, squat deep while keeping chest tall and knees tracking toes.', 'Legs', 'Easy', 3, 15, null, 20),
('Lunge Pulse', 'Hold bottom of lunge, pulse up and down 2-3 inches. Isometric endurance in lunge position.', 'Legs', 'Medium', 3, 20, null, 30),
('Lateral Band Walk', 'Band around ankles, take small steps sideways maintaining quarter-squat position throughout.', 'Legs', 'Easy', 3, null, 30, 20),
('Standing Hip Circle', 'Stand on one leg, trace large circles with opposite knee. Hip mobility and single-leg stability.', 'Legs', 'Easy', 3, 10, null, 20),
('Glute Bridge', 'Lie on back knees bent, drive hips to ceiling squeezing glutes at top. Lower with control.', 'Legs', 'Easy', 3, 15, null, 20),
('Single-Leg Glute Bridge', 'Same as glute bridge with one leg extended. Full glute contraction on working side.', 'Legs', 'Medium', 3, 12, null, 30),
('Hip Thrust', 'Shoulders on bench, hips hinged toward floor, drive hips to full extension squeezing glutes hard.', 'Legs', 'Medium', 3, 12, null, 30),
('Romanian Deadlift', 'Stand tall, hinge at hips with soft knees lowering weights along legs until hamstring tension. Drive up.', 'Legs', 'Medium', 3, 10, null, 45),
('Depth Jump', 'Step off box, land and immediately jump as high as possible. Minimal ground contact time.', 'Legs', 'Hard', 4, 6, null, 60),
('Single-Leg Box Jump', 'Jump onto box from one leg, land on same leg with control. Maximum single-leg power output.', 'Legs', 'Hard', 3, 5, null, 90),
('Squat Jump to Tuck', 'Squat, jump and tuck knees to chest, land softly. Explosive power with body awareness.', 'Legs', 'Hard', 3, 8, null, 60),
('Rear-Foot Elevated Split Squat', 'Rear foot elevated on bench, front foot far forward. Deep lunge with upright torso.', 'Legs', 'Medium', 3, 10, null, 45),
('Tempo Squat', 'Three-second descent, one-second pause at bottom, one-second rise. Builds eccentric strength.', 'Legs', 'Medium', 3, 8, null, 45),
('Jumping Lunge', 'Lunge, explode upward switching legs in air, land in opposite lunge. Alternate continuously.', 'Legs', 'Medium', 3, 10, null, 45),
('Wall-Supported Pistol', 'Use wall for light balance assist only while performing pistol squat. Wean off support over time.', 'Legs', 'Medium', 3, 8, null, 45),
('Broad Jump Series', 'Three consecutive broad jumps for maximum distance. Emphasizes horizontal power and landing.', 'Legs', 'Hard', 3, 5, null, 60),
('Seated Calf Raise', 'Seated, weight on knees, raise heels through full range of motion. Targets soleus specifically.', 'Legs', 'Easy', 3, 20, null, 20),
('Standing Calf Raise', 'Both feet on edge of step, lower heels below step level and raise to full tip-toe. Full range.', 'Legs', 'Easy', 3, 20, null, 20),
('Lateral Bound', 'Jump sideways off one foot, land on opposite foot. Control landing, pause, repeat other direction.', 'Legs', 'Medium', 3, 10, null, 45),
('Ice Skater', 'Lateral bounds with exaggerated lean, trailing leg sweeps behind. Continuous side-to-side.', 'Legs', 'Medium', 3, null, 30, 30),
('Hip Flexor March', 'Standing, drive knees up to hip height alternately with control. Targets hip flexors and balance.', 'Legs', 'Easy', 3, null, 30, 20),
('Terminal Knee Extension', 'Band behind knee, slight knee bend, fully extend knee against band resistance. VMO focused.', 'Legs', 'Easy', 3, 15, null, 20),
('Ankle Hops', 'Small rapid hops using only ankle plantarflexion, knees mostly straight. Builds ankle stiffness.', 'Legs', 'Easy', 3, null, 20, 30),
('Drop Squat', 'From standing drop explosively into deep squat position landing softly. Builds reactive strength.', 'Legs', 'Medium', 3, 10, null, 30),

-- CORE (30 new)
('Dead Bug', 'Lie on back, arms and knees at 90 degrees, lower opposite arm and leg toward floor. Press back.', 'Core', 'Easy', 3, 10, null, 30),
('Bird Dog', 'On hands and knees, extend opposite arm and leg simultaneously. Hold 2 seconds. Keep hips level.', 'Core', 'Easy', 3, 10, null, 20),
('Side Plank', 'Forearm on floor, body in straight line sideways. Hold. Stack feet or stagger for stability.', 'Core', 'Medium', 3, null, 30, 30),
('Side Plank Hip Dip', 'In side plank, lower and raise hip repeatedly. Adds dynamic demand to lateral chain.', 'Core', 'Medium', 3, 12, null, 30),
('Pallof Press', 'Band anchored at chest height to side, press arms straight ahead and return. Anti-rotation core.', 'Core', 'Medium', 3, 12, null, 30),
('Ab Wheel Rollout', 'From knees, roll wheel forward maintaining rigid torso, roll back. Never let hips drop.', 'Core', 'Hard', 3, 8, null, 60),
('Standing Ab Wheel', 'Full standing rollout — roll all the way to floor and back up. Elite core strength required.', 'Core', 'Hard', 3, 5, null, 90),
('Hanging L-Sit', 'From bar hang, maintain legs at 90 degrees (L position). Keep legs straight throughout.', 'Core', 'Hard', 3, null, 15, 60),
('Windshield Wiper', 'Hang from bar, raise legs to horizontal and rotate side to side like a windshield wiper.', 'Core', 'Hard', 3, 8, null, 60),
('Stir the Pot', 'Forearms on stability ball in plank, trace small circles with elbows. Extreme anti-rotation demand.', 'Core', 'Hard', 3, null, 20, 60),
('Copenhagen Plank', 'Side plank with top foot on elevated surface and bottom leg hanging. Adductor and core load.', 'Core', 'Hard', 3, null, 20, 60),
('Flutter Kick', 'Lie on back, arms at sides, legs 6 inches off floor. Alternate small rapid kicks. Back stays flat.', 'Core', 'Medium', 3, null, 30, 30),
('Scissor Kick', 'Like flutter kick but with larger alternating cross-body leg movements. Keep lower back pressed down.', 'Core', 'Medium', 3, null, 30, 30),
('Jackknife', 'Lie flat, simultaneously raise straight legs and upper body to meet in the middle. V position.', 'Core', 'Medium', 3, 12, null, 45),
('Russian Twist', 'Seated with knees bent and feet raised, rotate torso side to side. Add weight for challenge.', 'Core', 'Medium', 3, 20, null, 30),
('Bicycle Crunch', 'Alternate elbow to opposite knee in a pedaling motion. Full rotation each rep, no rushing.', 'Core', 'Medium', 3, 20, null, 30),
('Reverse Crunch', 'Lie on back, curl hips off floor bringing knees toward chest. Control the lower on the way down.', 'Core', 'Easy', 3, 15, null, 20),
('Straight-Leg Raise', 'Lie flat, raise straight legs to vertical and lower slowly without touching floor. Back flat.', 'Core', 'Medium', 3, 12, null, 30),
('Plank Reach', 'In forearm plank, extend one arm forward and hold 2 seconds. Alternate. Anti-rotation demand.', 'Core', 'Medium', 3, 10, null, 30),
('Plank Shoulder Tap', 'In push-up top position, tap opposite shoulder. Minimal hip rotation. Core stability under movement.', 'Core', 'Medium', 3, 12, null, 30),
('Long Lever Plank', 'Forearm plank with arms extended further forward than usual. Increases lever arm difficulty.', 'Core', 'Hard', 3, null, 30, 45),
('Hollow to Arch', 'Lying on floor, alternate between hollow body and arch body position. Full spinal range.', 'Core', 'Easy', 3, 10, null, 20),
('Tuck Up', 'From lying flat, simultaneously tuck knees to chest and sit up. Return to lying with control.', 'Core', 'Easy', 3, 15, null, 20),
('Seated Leg Raise', 'Sit on edge of bench, grip sides, raise straight legs to horizontal and lower. Strict form.', 'Core', 'Medium', 3, 12, null, 30),
('Dragon Flag Negative', 'Start horizontal on bench, lower slowly to floor maintaining rigid body. 5-second descent.', 'Core', 'Hard', 3, 5, null, 90),
('Weighted Sit-up', 'Full sit-up holding weight plate at chest. Controlled on the way down, powerful on the way up.', 'Core', 'Medium', 3, 12, null, 30),
('Hip Circles in Hollow', 'Maintain hollow body position while making small circles with both legs together. Extreme core demand.', 'Core', 'Hard', 3, null, 20, 60),
('Boat Pose Hold', 'Seated, legs straight at 45 degrees, arms parallel to floor. Full V-sit hold for time.', 'Core', 'Medium', 3, null, 20, 30),
('Plank to Downward Dog', 'Alternate between push-up top position and downward dog, pressing through straight arms each time.', 'Core', 'Easy', 3, 10, null, 20),
('Hanging Windshield Wiper', 'Full rotation version — legs go from horizontal on one side, through vertical, to other side.', 'Core', 'Hard', 3, 6, null, 90);
