
insert into public.exercises (name, description, muscle_group, difficulty, default_sets, default_reps, default_duration_seconds, default_rest_seconds) values

-- SHOULDERS (32 new)
('Handstand Kick-up Practice', 'Kick up to wall handstand repeatedly, focusing on straight body and active shoulder shrug at top.', 'Shoulders', 'Medium', 3, 8, null, 45),
('Freestanding Handstand Hold', 'Kick up and balance without wall support. Fingertip corrections, hollow body, active shrug.', 'Shoulders', 'Hard', 3, null, 10, 90),
('Handstand Walk', 'Walk on hands in a straight line. Keep body tight, steer with fingertips and shoulder shifts.', 'Shoulders', 'Hard', 3, null, 15, 90),
('Shoulder Press', 'Press weight from shoulders to full lockout overhead. Full extension at top, controlled lowering.', 'Shoulders', 'Medium', 3, 10, null, 45),
('Arnold Press', 'Start with palms facing you at shoulder height, press overhead rotating palms forward. Full range.', 'Shoulders', 'Medium', 3, 10, null, 45),
('Front Raise', 'Arms at sides, raise one or both arms to shoulder height in front. Slow and controlled lowering.', 'Shoulders', 'Easy', 3, 12, null, 30),
('Upright Row', 'Grip bar or bands at waist, pull to chin height with elbows flaring wide. Squeeze at top.', 'Shoulders', 'Medium', 3, 12, null, 30),
('Cuban Press', 'External rotation at 90 degrees followed by overhead press. Full shoulder health movement.', 'Shoulders', 'Easy', 3, 10, null, 30),
('Wall Walk', 'Start in push-up position feet near wall, walk feet up wall while walking hands toward wall.', 'Shoulders', 'Medium', 3, 8, null, 45),
('Wall Walk Hold', 'Walk up to chest-to-wall handstand position and hold. Maximum handstand-specific shoulder load.', 'Shoulders', 'Hard', 3, null, 15, 60),
('Handstand Push-up', 'Full freestanding or wall handstand push-up. Lower head to floor, press to full lockout.', 'Shoulders', 'Hard', 3, 5, null, 90),
('Half-Kneeling Press', 'Half-kneeling position, press single weight overhead. Eliminates leg drive, isolates shoulder.', 'Shoulders', 'Medium', 3, 10, null, 30),
('Trap-3 Raise', 'Lie at 45-degree angle on bench, raise arm in line with body angle. Lower trap strengthening.', 'Shoulders', 'Easy', 3, 15, null, 20),
('Reverse Fly', 'Hinge at hips, raise arms to sides squeezing rear delts. Counteracts internal rotation dominance.', 'Shoulders', 'Easy', 3, 15, null, 20),
('External Rotation', 'Elbow at 90 degrees by side or on surface, rotate forearm outward against band resistance.', 'Shoulders', 'Easy', 3, 15, null, 20),
('Internal Rotation', 'Elbow at 90 degrees, rotate forearm inward against band resistance. For rotator cuff balance.', 'Shoulders', 'Easy', 3, 15, null, 20),
('Bottoms-Up KB Press', 'Hold kettlebell upside down (bottom up), press overhead. Demands extreme shoulder stability.', 'Shoulders', 'Hard', 3, 8, null, 60),
('Single-Arm Landmine Press', 'One hand on end of bar in landmine, press at 45-degree angle overhead. Core and shoulder.', 'Shoulders', 'Medium', 3, 10, null, 30),
('Band Dislocate', 'Wide grip on band, keeping arms straight, pass band over head and behind back and return.', 'Shoulders', 'Easy', 3, 10, null, 20),
('Scapular Wall Slide', 'Back against wall, slide arms up in W-to-Y pattern. Trains scapular upward rotation.', 'Shoulders', 'Easy', 3, 12, null, 20),
('Overhead Hold Walk', 'Hold weight directly overhead with locked elbow, walk for distance maintaining alignment.', 'Shoulders', 'Medium', 3, null, 30, 30),
('Ring Support Hold', 'Support hold above rings with arms locked, rings turned out. Foundation of ring gymnastics.', 'Shoulders', 'Hard', 3, null, 20, 60),
('Ring Dip Support', 'Hold top of dip position on rings, rings turned out 45 degrees, maintain for time.', 'Shoulders', 'Hard', 3, null, 15, 60),
('Prone W Raise', 'Lie face down, arms in W shape (elbows bent, hands up), raise elbows off floor. Mid trap.', 'Shoulders', 'Easy', 3, 15, null, 20),
('Handstand Shrug', 'In wall handstand, perform small shoulder shrugs (elevation and depression). Active shoulder work.', 'Shoulders', 'Hard', 3, 10, null, 60),
('Kipping Swing', 'On bar, alternate between arch and hollow body in rhythmic kipping swing. Gymnastics conditioning.', 'Shoulders', 'Medium', 3, null, 30, 45),
('Push Press', 'Small knee dip, then drive weight overhead using leg momentum. More load than strict press.', 'Shoulders', 'Medium', 3, 8, null, 45),
('Alternating Lateral Raise', 'Raise one arm at a time to side, lower with control before raising the other. Slower tempo.', 'Shoulders', 'Easy', 3, 12, null, 20),
('Z-Press', 'Seated on floor legs straight in front, press weight overhead. Eliminates any leg or back compensation.', 'Shoulders', 'Hard', 3, 8, null, 60),
('YTWL Raise', 'Prone, perform Y, T, W, and L raise positions in sequence. Full rotator cuff and trapezius circuit.', 'Shoulders', 'Medium', 3, 8, null, 45),
('Cable Face Pull', 'Rope attachment at face height, pull to face with elbows high and wide. Rear delt and external rot.', 'Shoulders', 'Easy', 3, 15, null, 20),
('Handstand Pirouette', 'In wall handstand, practice rotating 180 degrees by shifting weight and walking hands around.', 'Shoulders', 'Hard', 3, 6, null, 90);
