
insert into public.exercises (name, description, muscle_group, difficulty, default_sets, default_reps, default_duration_seconds, default_rest_seconds, category, prehab_focus) values

-- SHOULDERS (20 prehab)
('Shoulder CARs', 'Controlled articular rotations — trace the largest circle possible with your shoulder while maintaining tension. Go slow, feel the edge of your range.', 'Shoulders', 'Easy', 2, 5, null, 15, 'prehab', 'activation'),
('Band External Rotation (90°)', 'Elbow at 90° at shoulder height, rotate forearm back against band resistance. Slow and controlled. Key rotator cuff activator before overhead work.', 'Shoulders', 'Easy', 3, 15, null, 20, 'prehab', 'activation'),
('Band Internal Rotation', 'Elbow at 90° at side, rotate forearm inward against band. Balance to external rotation work. Essential for shoulder health.', 'Shoulders', 'Easy', 3, 15, null, 20, 'prehab', 'activation'),
('Scapular Wall Slide', 'Back flat on wall, arms in W position, slide arms overhead into Y while maintaining wall contact. Trains scapular upward rotation pattern.', 'Shoulders', 'Easy', 3, 12, null, 20, 'prehab', 'mobility'),
('Prone Y Raise (prehab)', 'Lie face down, raise arms to Y position with thumbs up. Light load only. Lower trapezius activation for shoulder stability.', 'Shoulders', 'Easy', 3, 12, null, 20, 'prehab', 'activation'),
('Prone T Raise (prehab)', 'Lie face down, raise arms to T (shoulder height) with thumbs up. Rear deltoid and mid trapezius activation.', 'Shoulders', 'Easy', 3, 12, null, 20, 'prehab', 'activation'),
('Prone W Raise (prehab)', 'Lie face down, arms in W shape (elbows bent, hands up), raise off floor squeezing mid back. Lower trap focused.', 'Shoulders', 'Easy', 3, 12, null, 20, 'prehab', 'activation'),
('Sleeper Stretch', 'Lie on side on affected shoulder, bend elbow 90°, use other hand to gently press wrist toward floor. Posterior capsule stretch.', 'Shoulders', 'Easy', 3, null, 30, 15, 'prehab', 'mobility'),
('Cross-Body Shoulder Stretch', 'Pull one arm across chest with opposite hand, hold at point of tension. Posterior shoulder and rotator cuff mobility.', 'Shoulders', 'Easy', 3, null, 30, 10, 'prehab', 'mobility'),
('Band Pull-Apart (prehab)', 'Hold band at chest width with straight arms, pull apart to full extension. Rear delt and external rotator activation.', 'Shoulders', 'Easy', 3, 20, null, 20, 'prehab', 'activation'),
('Doorway Chest Stretch', 'Stand in doorway, place forearms on frame, lean forward until stretch is felt in chest and front shoulder. Anterior shoulder mobility.', 'Shoulders', 'Easy', 3, null, 30, 10, 'prehab', 'mobility'),
('Shoulder Pendulum', 'Lean forward, let arm hang freely, make small circles with gravity assisting. Joint decompression and gentle mobility warm-up.', 'Shoulders', 'Easy', 2, null, 30, 10, 'prehab', 'mobility'),
('Wall Angels', 'Stand with back flat on wall, arms overhead in Y, slowly bring elbows down to sides maintaining wall contact. Scapular control.', 'Shoulders', 'Easy', 3, 10, null, 20, 'prehab', 'stability'),
('Handstand Shoulder Shrug (prehab)', 'In wall handstand, perform small rhythmic shoulder shrugs (elevation and depression). Active shoulder end-range loading.', 'Shoulders', 'Hard', 3, 10, null, 45, 'prehab', 'strength'),
('Rotator Cuff ISOMETRIC', 'Press hand against wall at 90° elbow in each rotation direction. Hold 5 seconds each. Pain-free rotator cuff loading.', 'Shoulders', 'Easy', 3, null, 20, 15, 'prehab', 'strength'),
('Scapular Push-up (prehab)', 'In push-up top position, alternate between protracting (pushing scapulae apart) and retracting. Serratus anterior activation.', 'Shoulders', 'Easy', 3, 15, null, 20, 'prehab', 'activation'),
('GIRD Stretch', 'Glenohumeral internal rotation deficit stretch — lie on side, shoulder at 90°, gently press wrist toward floor. Essential for throwing athletes.', 'Shoulders', 'Easy', 3, null, 30, 15, 'prehab', 'mobility'),
('Shoulder Flexion Wall Walk', 'Stand facing wall, walk fingers up wall as high as possible, hold briefly. Shoulder flexion range of motion.', 'Shoulders', 'Easy', 3, 10, null, 15, 'prehab', 'mobility'),
('Cuban Press', 'From hang position, externally rotate to press overhead. Full shoulder health movement combining ER and press in one pattern.', 'Shoulders', 'Easy', 3, 10, null, 30, 'prehab', 'strength'),
('Overhead Banded Distraction', 'Band anchored low, place around wrist, raise arm overhead, allow band to gently distract the shoulder joint. Capsular mobility.', 'Shoulders', 'Easy', 2, null, 45, 15, 'prehab', 'mobility'),

-- ARMS (15 prehab)
('Wrist CARs', 'Controlled articular rotations of the wrist — trace the largest circle possible in both directions under tension. Essential for gymnastics.', 'Arms', 'Easy', 2, 5, null, 10, 'prehab', 'activation'),
('Wrist Flexor Stretch', 'Arm extended, palm up, gently press fingers back toward forearm. Hold at point of tension. Forearm flexor mobility.', 'Arms', 'Easy', 3, null, 30, 10, 'prehab', 'mobility'),
('Wrist Extensor Stretch', 'Arm extended, palm down, gently press fingers toward floor. Hold. Forearm extensor and wrist mobility.', 'Arms', 'Easy', 3, null, 30, 10, 'prehab', 'mobility'),
('Wrist Weight Shifts', 'On all fours, slowly shift weight forward onto fingertips and back. Gradual wrist loading for conditioning.', 'Arms', 'Easy', 3, null, 30, 20, 'prehab', 'strength'),
('Fist Push-up Wrist Warm-up', 'Push-ups on fists to keep wrist neutral. Wrist conditioning without full extension load.', 'Arms', 'Easy', 3, 8, null, 20, 'prehab', 'strength'),
('Rice Bucket — Finger Extensions', 'Plunge hand into rice bucket, open fingers against resistance. Finger extensor strengthening for grip balance.', 'Arms', 'Easy', 3, null, 30, 20, 'prehab', 'strength'),
('Elbow Flexor Stretch', 'Extend arm fully, rotate palm up, gently press wrist toward floor. Bicep and elbow flexor stretch.', 'Arms', 'Easy', 3, null, 30, 10, 'prehab', 'mobility'),
('Tricep Cross-Body Stretch', 'Raise arm, bend elbow behind head, use other hand to gently press elbow. Tricep and elbow mobility.', 'Arms', 'Easy', 3, null, 30, 10, 'prehab', 'mobility'),
('Active Wrist Pronation/Supination', 'Elbow at 90°, actively rotate forearm through full pronation and supination range. Radioulnar joint activation.', 'Arms', 'Easy', 3, 15, null, 15, 'prehab', 'activation'),
('Finger Tendon Glide', 'Move fingers through: straight, hook fist, full fist, straight knuckle fist. Tendon gliding exercises for finger health.', 'Arms', 'Easy', 3, 10, null, 10, 'prehab', 'activation'),
('Wrist ISOMETRIC Loading', 'Press palm against wall in flexion, extension, and lateral deviation. Hold each direction. Pain-free wrist loading protocol.', 'Arms', 'Easy', 3, null, 20, 15, 'prehab', 'strength'),
('Hammer Curl (light prehab)', 'Neutral grip curl with very light load. Elbow tendon conditioning. Brachioradialis activation.', 'Arms', 'Easy', 3, 15, null, 20, 'prehab', 'strength'),
('Reverse Wrist Curl', 'Forearms on surface, wrists hanging off edge, extend wrist against gravity. Wrist extensor strengthening.', 'Arms', 'Easy', 3, 15, null, 20, 'prehab', 'strength'),
('Grip Squeeze (towel)', 'Squeeze a rolled towel as hard as possible for 5 seconds, relax. Grip strengthening and forearm endurance.', 'Arms', 'Easy', 3, null, 30, 15, 'prehab', 'strength'),
('Pinch Grip Holds', 'Pinch a plate or book between thumb and fingers, hold for time. Pinch strength and thumb tendon conditioning.', 'Arms', 'Easy', 3, null, 20, 20, 'prehab', 'strength'),

-- BACK (15 prehab)
('Cat-Cow', 'On all fours, alternate between arching and rounding the spine with full breath. Spinal mobility and segmental control.', 'Back', 'Easy', 3, 10, null, 10, 'prehab', 'mobility'),
('Child''s Pose', 'Kneel, sit back on heels, reach arms overhead on floor. Hold. Thoracic spine and lat stretch with gentle traction.', 'Back', 'Easy', 3, null, 45, 10, 'prehab', 'mobility'),
('Thoracic Extension over Foam Roller', 'Sit with roller behind mid-back, support head, extend over roller one segment at a time. Thoracic mobility.', 'Back', 'Easy', 3, null, 30, 15, 'prehab', 'mobility'),
('Thread the Needle', 'On all fours, thread one arm under body reaching to opposite side. Thoracic rotation mobility essential for gymnastics.', 'Back', 'Easy', 3, null, 30, 10, 'prehab', 'mobility'),
('Bird Dog (slow prehab)', 'On all fours, extend opposite arm and leg with 3-second hold at top. Deep multifidus and lumbar stabilizer activation.', 'Back', 'Easy', 3, 8, null, 20, 'prehab', 'stability'),
('McGill Curl-Up', 'One knee bent, hands under lumbar, partial sit-up maintaining neutral spine. Spine-sparing core stability drill.', 'Back', 'Easy', 3, 10, null, 20, 'prehab', 'stability'),
('Side-Lying Thoracic Rotation', 'Lie on side knees bent, top arm sweeps overhead to opposite side. Thoracic rotation with rib cage opening.', 'Back', 'Easy', 3, null, 30, 10, 'prehab', 'mobility'),
('Lumbar ISOMETRIC Hold', 'Prone on elbows (sphinx position), gently press pubic bone down, feel lower back muscles engage. Lumbar stabilizer activation.', 'Back', 'Easy', 3, null, 20, 15, 'prehab', 'activation'),
('Prone Press-Up', 'Lie face down, place hands under shoulders, press upper body up while hips stay down. McKenzie extension for disc health.', 'Back', 'Easy', 3, 10, null, 15, 'prehab', 'mobility'),
('Quadruped Hip Extension', 'On all fours, extend one leg back to hip height maintaining neutral pelvis. Glute activation protecting lower back.', 'Back', 'Easy', 3, 12, null, 20, 'prehab', 'activation'),
('Supine Spinal Twist', 'Lie on back, bring one knee across body while keeping shoulders flat. Lumbar rotation and paraspinal muscle release.', 'Back', 'Easy', 3, null, 45, 10, 'prehab', 'mobility'),
('Face Pull (prehab)', 'Rope at face height, pull to face with elbows high. Posterior shoulder chain activation protecting the thoracic spine.', 'Back', 'Easy', 3, 15, null, 20, 'prehab', 'activation'),
('Pallof Press Anti-Rotation', 'Band anchored at chest height, press straight ahead and return. Trains spine to resist rotation under load.', 'Back', 'Medium', 3, 12, null, 30, 'prehab', 'stability'),
('Scapular Retraction Hold', 'Squeeze shoulder blades together and hold for 5 seconds. Mid-trap activation essential for thoracic spine posture.', 'Back', 'Easy', 3, null, 20, 15, 'prehab', 'activation'),
('Hip Hinge Pattern', 'Hinge at hips with flat back, dowel touching head/back/tailbone. Teaches proper loading mechanics protecting lumbar spine.', 'Back', 'Easy', 3, 10, null, 20, 'prehab', 'stability');
